### ISSUE TITLE
tx index not required

### ISSUE THREAD

**Issue by chris-belcher** [tailsjoin/tailsjoin#1]
I've noticed your script sets txindex=1
This is actually not required for joinmarket. It only queries the mempool and utxo set.
Also this means the hard disk size requirement can be dropped to about 40GB.

When the new release of bitcoin core with pruning and wallet enabled comes out, someone could run this with a full node on tails using only about 1GB of space.

**Comment by tailsjoin** [comment]
Thank you. 

Fixed here: https://github.com/tailsjoin/tailsjoin/commit/130280dd83f6f2c45f14eb56c8a91f5aab242f5f

Edit: Linked proper commit.
